name: Python package

on:
  push:
    paths-ignore:
    - '**.rst'
    - 'tests/test_vllm.py' # requires vllm to be installed

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with pytest
      run: |
        pytest

  contrib-readme-job:
    runs-on: ubuntu-latest
    name: A job to automate contrib in readme
    permissions:
      contents: write
      pull-requests: write
    steps:
        - name: Contribute List
          uses: akhilmhdh/contributors-readme-action@v2.3.10
          env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
